version: '2'
services:
  ejabberd:
    image: ejabberd/ecs
    container_name: ejabberd
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    volumes:
      - ./volumes/home:/home/ejabberd/conf